-- ============================================================
-- Vaguinha - Schema PostgreSQL (Supabase)
-- ============================================================
-- Pode ser executado mais de uma vez (idempotente):
--   * banco vazio            → cria tudo + evento "Corrida da FAB" com 13 áreas;
--   * banco da versão antiga → (sem eventos) migra as 13 áreas e todo o
--                              histórico para o evento "Corrida da FAB".
-- ============================================================

-- Tipos de veículo
CREATE TABLE IF NOT EXISTS tipo_veiculo (
    id   SMALLINT PRIMARY KEY,       -- 1 = Carro, 2 = Moto
    nome VARCHAR(20) NOT NULL
);

INSERT INTO tipo_veiculo (id, nome) VALUES (1, 'Carro'), (2, 'Moto')
ON CONFLICT (id) DO NOTHING;

-- Eventos (ex.: "Corrida da FAB")
CREATE TABLE IF NOT EXISTS evento (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(80) NOT NULL,
    criado_em TIMESTAMP   NOT NULL DEFAULT (NOW() AT TIME ZONE 'America/Sao_Paulo')
);

-- Áreas de cada evento (a tabela se chama "local" por compatibilidade)
CREATE TABLE IF NOT EXISTS local (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id INTEGER     NOT NULL REFERENCES evento(id) ON DELETE CASCADE,
    nome      VARCHAR(60) NOT NULL,
    cor       VARCHAR(20) NOT NULL DEFAULT '#1f6f8b',
    cap_carro INTEGER     NOT NULL DEFAULT 0 CHECK (cap_carro >= 0),
    cap_moto  INTEGER     NOT NULL DEFAULT 0 CHECK (cap_moto >= 0),
    ordem     INTEGER     NOT NULL DEFAULT 0
);

-- Movimentação (histórico de entradas e saídas)
CREATE TABLE IF NOT EXISTS movimentacao (
    id              BIGSERIAL PRIMARY KEY,
    tipo_veiculo_id SMALLINT    NOT NULL REFERENCES tipo_veiculo(id),
    local_id        INTEGER     NOT NULL REFERENCES local(id) ON DELETE CASCADE,
    movimentacao    VARCHAR(10) NOT NULL CHECK (movimentacao IN ('entrada','saida')),
    horario         TIMESTAMP   NOT NULL DEFAULT (NOW() AT TIME ZONE 'America/Sao_Paulo')
);

-- ============================================================
-- Migração da versão antiga (áreas fixas 1..13, sem eventos)
-- ============================================================
DO $$
DECLARE
    v_evento INTEGER;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'local' AND column_name = 'evento_id'
    ) THEN
        DROP VIEW IF EXISTS vw_ocupacao;  -- depende das colunas alteradas abaixo

        INSERT INTO evento (nome) VALUES ('Corrida da FAB') RETURNING id INTO v_evento;

        ALTER TABLE local ADD COLUMN evento_id INTEGER REFERENCES evento(id) ON DELETE CASCADE;
        ALTER TABLE local ADD COLUMN cor   VARCHAR(20) NOT NULL DEFAULT '#1f6f8b';
        ALTER TABLE local ADD COLUMN ordem INTEGER     NOT NULL DEFAULT 0;
        UPDATE local SET
            evento_id = v_evento,
            ordem     = id,
            cor       = CASE WHEN id <= 4 THEN '#1f6f8b'
                             WHEN id <= 8 THEN '#2e6b3e'
                             ELSE '#5b4b8a' END;
        ALTER TABLE local ALTER COLUMN evento_id SET NOT NULL;

        -- id das áreas passa a ser gerado automaticamente (para criar novas)
        ALTER TABLE movimentacao DROP CONSTRAINT IF EXISTS movimentacao_local_id_fkey;
        ALTER TABLE local        ALTER COLUMN id       TYPE INTEGER;
        ALTER TABLE movimentacao ALTER COLUMN local_id TYPE INTEGER;
        ALTER TABLE local ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        PERFORM setval(pg_get_serial_sequence('local', 'id'),
                       (SELECT COALESCE(MAX(id), 0) + 1 FROM local), false);
        ALTER TABLE movimentacao ADD CONSTRAINT movimentacao_local_id_fkey
            FOREIGN KEY (local_id) REFERENCES local(id) ON DELETE CASCADE;
    END IF;
END $$;

-- Horário no fuso de Brasília (o servidor do Supabase roda em UTC)
ALTER TABLE movimentacao
    ALTER COLUMN horario SET DEFAULT (NOW() AT TIME ZONE 'America/Sao_Paulo');

CREATE INDEX IF NOT EXISTS idx_local_evento   ON local (evento_id);
CREATE INDEX IF NOT EXISTS idx_mov_local_tipo ON movimentacao (local_id, tipo_veiculo_id);

-- ============================================================
-- Evento inicial (só se o banco ainda não tiver nenhum evento)
-- ============================================================
DO $$
DECLARE
    v_evento INTEGER;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM evento) THEN
        INSERT INTO evento (nome) VALUES ('Corrida da FAB') RETURNING id INTO v_evento;
        INSERT INTO local (evento_id, nome, cap_carro, cap_moto, cor, ordem) VALUES
            (v_evento, 'Área 1',  150, 50, '#1f6f8b',  0),
            (v_evento, 'Área 2',  120, 40, '#1f6f8b',  1),
            (v_evento, 'Área 3',  120, 40, '#1f6f8b',  2),
            (v_evento, 'Área 4',  100, 30, '#1f6f8b',  3),
            (v_evento, 'Área 5',  100, 30, '#2e6b3e',  4),
            (v_evento, 'Área 6',   80, 25, '#2e6b3e',  5),
            (v_evento, 'Área 7',   80, 25, '#2e6b3e',  6),
            (v_evento, 'Área 8',   60, 20, '#2e6b3e',  7),
            (v_evento, 'Área 9',   60, 20, '#5b4b8a',  8),
            (v_evento, 'Área 10',  50, 15, '#5b4b8a',  9),
            (v_evento, 'Área 11',  50, 15, '#5b4b8a', 10),
            (v_evento, 'Área 12',  40, 10, '#5b4b8a', 11),
            (v_evento, 'Área 13',  40, 10, '#5b4b8a', 12);
    END IF;
END $$;

-- ============================================================
-- Segurança (Supabase): tabelas do schema "public" ficam expostas na API REST
-- pública do projeto (chave "anon"). Ativar RLS sem criar políticas bloqueia
-- esse acesso; o app conecta como dono das tabelas (postgres) e não é afetado.
-- ============================================================
ALTER TABLE tipo_veiculo ENABLE ROW LEVEL SECURITY;
ALTER TABLE evento       ENABLE ROW LEVEL SECURITY;
ALTER TABLE local        ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimentacao ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- View de saldo atual (ocupação = entradas - saídas) por evento e área.
-- security_invoker: a view respeita o RLS acima (PostgreSQL 15+).
-- ============================================================
DROP VIEW IF EXISTS vw_ocupacao;
CREATE VIEW vw_ocupacao WITH (security_invoker = true) AS
SELECT
    l.evento_id,
    m.local_id,
    m.tipo_veiculo_id,
    SUM(CASE WHEN m.movimentacao = 'entrada' THEN 1 ELSE -1 END) AS ocupados
FROM movimentacao m
JOIN local l ON l.id = m.local_id
GROUP BY l.evento_id, m.local_id, m.tipo_veiculo_id;
